name: run pytest

on:
  push: 
    branches: 
      - main

jobs:

  build:
    run-on: ubuntu-latest
    
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install pytest

  - name: Run tests
    run: |
      pytest tests/test_calculator.py --verbose
  
